### ISSUE TITLE
Error 500 on Redirect

### ISSUE THREAD

**Issue by tagadajohn** [RyanBayne/TwitchPress#171] opened 2017-11-16 23:03 UTC
Hi,
When login in I get this error.
https://imgur.com/a/JWY8K

I tried with 2 differents account.

maybe my redirect url isn't right i've put the default folder of the wordpress installation domainname.com/gaminator

thank you
cheer
ps: I'm j1mTV from discord.

**Comment by RyanBayne** [comment] 2017-11-16 23:16
I have not run tests on an installation of WordPress that is not in the main directory. 

So I'm wondering if that is the issue but someone else reported the same error and I don't think their installation was in a folder. This will now be the priority issue.

**Comment by tagadajohn** [comment] 2017-11-17 03:06
to get you more infos I tried to put the website on the root folder of my hosting and still get the same error
https://imgur.com/SW6DE70
tried with 2 account.
here is my hosting configuration if it can help maybe I miss a required feature.
https://i.imgur.com/DBAA9qa.jpg

cya

**Comment by RyanBayne** [comment] 2017-11-30 21:05
Recent users have reported this problem has been fixed when using the recent update. 

One user has stated it happened to them since but the circumstances could be different. There are improvements in some users sites for sure and I re-created the issue on my own site. Meaning I took measures to fix it that worked for me also. 

The issue stays open pending further investigation. 

The 500 could be caused by a lack of scopes providing the right permissions or I have made a mistake and generated the wrong token for the wrong call.

**Comment by unitedfusionentertainment** [comment] 2017-11-30 21:53
I have found on my own installation that this issue only persists when I use my main twitch account to log in. I am looking into my own configuration to see if I can find a fix and if I do I will post details here and in discord.

**Comment by RyanBayne** [comment] 2017-12-08 12:46
This issue has been resolved by making a clearer distinction between user and application tokens.

There was a confusion over how they are used and the wrong token would create 500. The work I done to sort this now leads the way to individual visitors having sessions and being able to use automated services on any WP.

**Comment by RyanBayne** [comment] 2017-12-17 01:31
I have had further confirmation on this issue being resolved but the solution has not been the same for all users. 

Someone switched hosting and found that the same site on a new host worked fine. 

Someone also switched PHP version from 7 to 5.6 and things worked fine. This is strange because I work with 7. We came to the conclusion that because it worked on version 7 on the new host that the old host was doing something very different. 

I suspect that it was the detection of Twitch API or any similar API being used and prevented to reduce bandwidth on a WP hosting package. This issue has cost me 100 hours easily including it triggering a range of required changes. 

Case CLOSED! :)

**Closed** 2017-12-17 01:31 UTC
Labels: bug
